name: Actions Workflow

on:
  push:
    branches:
      - develop
      - main
      - 'release/*'
      - master
      - 'feature/*'
  pull_request:
    types: [opened, edited, closed]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: List Files After Checkout
        run: |
          pwd
          ls -al

      - name: Simple JavaScript Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Teodik Meserkhani

      - name: Greeting Time
        run: echo "${{steps.greet.outputs.time}}"