name: Decrypt the encrypted file by GunPG

on: [push]

jobs:
  Decrypt:
    run-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2.3.4
    - name: Decrypt secret.json
      run: gpg --quite --batch --yes --decrypt --passphrase="${{secrets.PASSPHASE}}" --output $GITHUB_WORKSPACE/secret.json secret.json.gpg
    - name: Print json file
      run: cat secret.json